FROM centos:8

RUN dnf install -y epel-release

RUN dnf groupinstall -y development

RUN dnf install -y git which

RUN curl --silent --location https://rpm.nodesource.com/setup_12.x | bash - && \
yum install -y nodejs

RUN dnf -y --enablerepo=PowerTools install glibc-static

RUN dnf module -y install python27

RUN git clone https://github.com/c9/core.git /c9sdk && cd /c9sdk && scripts/install-sdk.sh

RUN mkdir /c9sdk/workspace

WORKDIR /c9sdk/workspace

EXPOSE 8181