version: '3'
services:
  node:
    container_name: node
    build:
      context: ./
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - ./conf/.bashrc:/root/.bashrc
    tty: true

  mariadb:
    container_name: mariadb
    build:
      context: ./
      dockerfile: Dockerfile_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: node
    volumes:
      - ./mysql:/var/lib/mysql

  # cloud9:
  #   container_name: cloud9
  #   build:
  #     context: ./
  #     dockerfile: dockerfile_cloud9
  #   ports:
  #     - 8181:8181
  #     - 3000:3000
  #   command: "node /c9sdk/server.js -w /c9sdk/workspace --port 8181 --listen 0.0.0.0 --auth :"
